title: Collin Riddle
logo: https://lh3.googleusercontent.com/pw/AP1GczPi3rQRqEixC7o6J1hKAVyOE-W9p-88Lt-8olJTDW3dzFbUqVqy21z2d9nUARiiHsB20etA_JbvxBzh6N3z99hupMv2A64j5SIdrPCL-1s0lV-TMhY=w2400
description: My Portfolio
show_downloads: true
theme: jekyll-theme-minimal

